Add auth parameter for detector and enable auth by default
streamnative/charts pull request #424
Opened 2021-12-20 03:15 UTC by ignacioli

#423

2021-12-20 03:17 UTC, ignacioli commented
pulsar_detector image : keep same as charts sn-platform.

2021-12-23 21:30 UTC, sijie commented
@ignacioli Can you resolve the conflict?

2021-12-23 21:37 UTC, sijie requested changes

2021-12-23 21:37 UTC, sijie commented on charts/pulsar/templates/detector/pulsar-detector-statefulset.yaml
>            bin/pulsar-detector -service-url pulsar://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}:{{ .Values.broker.ports.pulsar }};
Don't we need to delete this line?

2021-12-23 21:37 UTC, sijie commented on charts/pulsar/values.yaml
> +  pulsar_detector: true
I don't think we should turn this one by default.

2021-12-23 21:37 UTC, sijie commented on charts/pulsar/values.yaml
> +    enabled: true
Same comment. We shouldn't turn this one by default

2021-12-24 01:02 UTC, closed without merging