Add the chart of pulsar resources operator
streamnative/charts pull request #584
Opened 2022-04-01 08:34 UTC by FushuWang

### Motivation

Add the chart of pulsar resources operator

### Modifications

Add the chart of pulsar resources operator

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

Check the box below.

Need to update docs? 

- [x] `doc`

2022-04-02 08:45 UTC, fantapsody approved these changes

2022-04-06 02:34 UTC, MarvinCai approved these changes

2022-04-24 14:39 UTC, maxsxu requested changes
Left a comment due to the failed CI

2022-04-24 14:39 UTC, maxsxu commented on charts/pulsar-resources-operator/tests/deployment_test.yaml
> +suite: test deployment
Missing license header.
Or skip license test in the `license_test.go`

2022-04-24 14:39 UTC, maxsxu commented on charts/pulsar-resources-operator/tests/serviceaccount_test.yaml
> +suite: test service account
Missing license header.
Or skip license test in the `license_test.go`

2022-05-04 13:11 UTC, ericsyh commented
@FushuWang @fantapsody Just check with you will we put the resource operator charts under `streamnative/charts` repo or `streamnative/pulsar-resource-operator` repo?

2022-05-05 06:04 UTC, fantapsody commented
> @FushuWang @fantapsody Just check with you will we put the resource operator charts under `streamnative/charts` repo or `streamnative/pulsar-resource-operator` repo?

It will be in `streamnative/pulsar-resource-operator`, I think we can close this one? @FushuWang

2022-05-05 08:17 UTC, FushuWang commented
> > @FushuWang @fantapsody Just check with you will we put the resource operator charts under `streamnative/charts` repo or `streamnative/pulsar-resource-operator` repo?
> 
> It will be in `streamnative/pulsar-resource-operator`, I think we can close this one? @FushuWang

Yeah, I will close it @ericsyh @fantapsody

2022-05-05 08:17 UTC, closed without merging