[BREAK Change]: remove local_storage config in sn-platform chart
streamnative/charts pull request #892
Opened 2022-11-04 13:29 UTC by ericsyh

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #817 

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

The `local_storage` config in sn-platform chart is used to bind with the `streamnative/local-storage-provisioner`. We should remove this config and recommend users to config with `storageClassName`

### Modifications

Remove `local_storage` config

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

2022-11-09 12:35 UTC, maxsxu requested changes
@ericsyh The CI error has been fixed by https://github.com/streamnative/charts/pull/899. Need to rebase the master branch.

2022-11-10 02:50 UTC, maxsxu approved these changes

2022-11-28 02:21 UTC, Huanli-Meng commented
I think we also need to remove the `local_storage` config from SNP 1.8 docs.

2022-12-01 03:54 UTC, ericsyh commented
@fantapsody @FushuWang @ciiiii @tuteng @urfreespace PTAL

2022-12-02 01:44 UTC, urfreespace approved these changes

2022-12-02 01:45 UTC, merged