Solve the conflict generated in last commit
streamnative/charts pull request #972
Opened 2023-03-08 15:06 UTC by AlvaroStream

### Motivation

There is an issue on the file.

### Modifications

Just fix a conflict, not validated

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Documentation
Need to update docs? 

- [ ] `doc-required` 
- [x] `no-need-doc` 

 no functionality change
  
- [ ] `doc`

2023-03-08 17:41 UTC, zerbitx approved these changes

2023-03-09 02:34 UTC, maxsxu commented on charts/sn-platform/templates/tls/tls-cert-internal-issuer.yaml
>  {{- end }}
Missing the end `{{- end }}`

2023-03-09 02:34 UTC, maxsxu requested changes
Missing a `{{- end }}` in the end

2023-03-09 12:50 UTC, ericsyh commented
@AlvaroStream @maxsxu Fixed with https://github.com/streamnative/charts/commit/5097b3b1a1bd72042f60f20647b864d0504b33f3

2023-03-09 12:50 UTC, closed without merging